services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example
      POSTGRES_PASSWORD: "5J9lAz5TvxglPGcHFazEnqOI3W4hRBrr"
    volumes:
      - example_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "hKngwFmvQaOYqbPjhxjv0Q2g-bwHX5M6"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example_test
      POSTGRES_PASSWORD: "QWoZ-TkwipduZHd2bVupbZk-ZadI4Uwp"
    volumes:
      - example_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "lO5DlKmR6upEyVNhVQ__sXw-QfmLjBvs"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  example_data:
  example_test_data:
